const dummyData = [
  {
    imageNo: 1,
    address: '/images/macbook1.jpeg',
    title: '맥북 1',
    division: 'mac',
    date: '2024-01-25',
    content: 'mac판매합니다.',
  },
  { 
    imageNo: 2,
    address: 'images/ipad1.jpeg',
    title: '아이패드1',
    division: 'ipad',
    date: '2024-01-26',
    content: 'ipad팝니다.',
  },
  {
    imageNo: 3,
    address: 'path/to/image3.jpg',
    title: 'Image 3',
    division: 'mac',
    date: '2024-01-27',
    content: 'mac판매합니다.',
  },
  {
    imageNo: 4,
    address: 'path/to/image4.jpg',
    title: 'Image 4',
    division: 'mac',
    date: '2024-01-28',
    content: 'mac판매합니다.',
  },
  {
    imageNo: 5,
    address: 'path/to/image5.jpg',
    title: 'Image 5',
    division: 'ipad',
    date: '2024-01-29',
    content: 'ipad팝니다.',
  },
  {
    imageNo: 6,
    address: 'path/to/image6.jpg',
    title: 'Image 6',
    division: 'iphone',
    date: '2024-01-30',
    content: 'iphone팝니다.',
  },
  {
    imageNo: 7,
    address: 'path/to/image7.jpg',
    title: 'Image 7',
    division: 'iphone',
    date: '2024-01-31',
    content: 'iphone팝니다.',
  },
  {
    imageNo: 8,
    address: 'path/to/image8.jpg',
    title: 'Image 8',
    division: 'iphone',
    date: '2024-02-01',
    content: 'iphone팝니다.',
  },
  {
    imageNo: 9,
    address: 'path/to/image9.jpg',
    title: 'Image 9',
    division: 'iphone',
    date: '2024-02-02',
    content: 'iphone팝니다.',
  },
  {
    imageNo: 10,
    address: 'path/to/image10.jpg',
    title: 'Image 10',
    division: 'etc',
    date: '2024-02-03',
    content: '기타 판매합니다.',
  },
];

export default dummyData;
